# Shape Optimizer Configuration
optimization_type: SA # can be SA, DSA
combination_type: zip # can be grid (cartesian product), zip
max_processes: 5
database_name: experiments.db
table_name: fast_test # if bool or null, table = x{x}y{y}n{num_ellipses}lambda{linear_pen}_opt{optimization_type}
n_runs: 5 # number of trials per configuration

geometric_params:
  geometric_config:
    x_max: 1.0
    y_max: 1.0
    MW_x: 0.3
    ME_x: 0.7
  h: 0.0125
  heat_sources: 10.0
  base_temp: 0.0
  num_ellipses: 4

penalizations:
  linear: 7.5

kwargs_SA: #SA
  initial_temp: 1000
  min_temp: 0.001
  cooling_rate: 0.995
  track_file_name: true
  gen_seed: 0 # 0 = no seed
  perturbation: [0.08, 0.08, 4.0, 6.0, 4.0]

kwargs_DSA: #DSA
  initial_temp: 1000.0
  min_temp: 0.01
  cooling_rate_max: 0.99
  cooling_rate_min: 0.95
  base_markov_length: 5 # 15 * n_ellipses
  num_configs: 10 # 10 * (n_ellipses + 1)
  initial_perturbation: [0.08, 0.08, 4.0, 8.0, 4.0]
  min_perturbation: [0.04, 0.04, 1.0, 2.0, 1.0]
  perturbation_update: 0.9
  min_cost_gap: 0.01
  track_file_name: true
  gen_seed: 0 # 0 = no seed