# Shape Optimizer Configuration
optimization_type: SA # can be SA, DSA
combination_type: lhs # can be grid (cartesian product), zip, lhs
n_lhs_samples: 15 # default = 10
max_processes: 2
database_name: experiments.db
table_name: test_new_delaunay # if bool or null, table = x{x}y{y}n{num_ellipses}lambda{linear_pen}_opt{optimization_type}
n_runs: 2 # number of trials per configuration

# Problem parameters
geometric_params:
  geometric_config:
    x_max: 1.0
    y_max: 1.0
    MW_x: 0.3
    ME_x: 0.7
  h: 0.02
  heat_sources: 10.0
  base_temp: 0.0
  num_ellipses: 4

penalizations:
  linear: 15.0

# Optimization parameters
kwargs_SA:
  initial_temp: 1000
  min_temp: 0.001
  cooling_rate: 0.995
  perturbation: [0.06, 0.06, 3.0, 1.0, 3.0]
  track_file_name: true
  gen_seed: 0 # 0 = no seed*
  improvement_threshold: 75 # default = 50


kwargs_DSA:
  initial_temp: 1000.0
  min_temp: 0.001
  cooling_rate_max: 0.99
  cooling_rate_min: 0.98
  base_markov_length: 15 # 15 * n_ellipses
  num_configs: 10 # 10 * (n_ellipses + 1)
  initial_perturbation: [0.08, 0.08, 4.0, 6.0, 4.0]
  min_perturbation: [0.008, 0.008, 0.4, 0.6, 0.4]
  perturbation_update: 0.995
  min_cost_gap: 0.01
  track_file_name: true
  gen_seed: 0 # 0 = no seed