"""
Bindings for Ellipse and SquareSolver using maniFEM
"""
from __future__ import annotations
import numpy
import typing
__all__ = ['Ellipse', 'EllipseBundle', 'SquareSolver']
class Ellipse:
    bounds: numpy.ndarray[numpy.float64[2, 1]]
    center: numpy.ndarray[numpy.float64[2, 1]]
    parametrize_matrix: numpy.ndarray[numpy.float64[2, 2]]
    quadratic_form: numpy.ndarray[numpy.float64[2, 2]]
    def __init__(self, x: float, y: float, A: float, B: float, C: float) -> None:
        ...
    def area(self) -> float:
        ...
    def bounding_half(self) -> numpy.ndarray[numpy.float64[2, 1]]:
        ...
    def derivative_at(self, t: float) -> numpy.ndarray[numpy.float64[2, 1]]:
        ...
    def evaluate_at(self, point: numpy.ndarray[numpy.float64[2, 1]]) -> float:
        ...
    def height(self) -> float:
        ...
    def is_inside(self, point: numpy.ndarray[numpy.float64[2, 1]]) -> bool:
        ...
    def point_at(self, t: float) -> numpy.ndarray[numpy.float64[2, 1]]:
        ...
    def second_derivative_at(self, t: float) -> numpy.ndarray[numpy.float64[2, 1]]:
        ...
    def width(self) -> float:
        ...
class EllipseBundle:
    bundle: list[Ellipse]
    def __init__(self, geometric_config: dict[str, float], h: float, num_ellipses: int) -> None:
        ...
    def add(self, new_ellipse: Ellipse) -> None:
        ...
    def area(self) -> float:
        ...
    def generate_random(self, seed: int = 0, max_attempts: int = 10000) -> None:
        ...
    @property
    def ME_x(self) -> float:
        ...
    @property
    def MW_x(self) -> float:
        ...
    @property
    def h(self) -> float:
        ...
    @property
    def x_max(self) -> float:
        ...
    @property
    def y_max(self) -> float:
        ...
class SquareSolver:
    base_temp: float
    h: float
    heat_sources: float
    @typing.overload
    def __init__(self, geometric_config: dict[str, float], h: float, heat_sources: float, base_temp: float, export_domain: bool, export_mesh: bool) -> None:
        ...
    @typing.overload
    def __init__(self, geometric_config: dict[str, float], h: float, heat_sources: float, base_temp: float) -> None:
        ...
    def solve(self, bundle: EllipseBundle) -> float:
        ...
    def solve_frontal(self, bundle: EllipseBundle) -> float:
        ...
    @property
    def export_domain(self) -> bool:
        ...
    @property
    def export_result(self) -> bool:
        ...
